FROM postgres:latest

# Environment variables for customization
ENV POSTGRES_DB=svuserdb
ENV POSTGRES_USER=svuseruser
ENV POSTGRES_PASSWORD=nosecret

# Optionally, you can provide a custom initialization SQL script
# COPY init.sql /docker-entrypoint-initdb.d/

EXPOSE 5432

#CMD ["postgres"]  # Uncomment this line if you want to use the default CMD from the base image